package crb.c64;

import java.util.ArrayList;
import java.util.List;

/** Names of the Craft 64 HUD textures (assets/crossover_rebuilt/textures/c64/NAME.png), generated by Tools/c64_art.py. */
public final class C64Art {
    private C64Art() { }
    public static final String[] NAMES;
    /** Vanilla textures the Craft 64 HUD draws (ammo icons). */
    public static final String[] VANILLA = { "textures/item/iron_nugget.png", "textures/item/gold_nugget.png", "textures/item/firework_rocket.png", "textures/item/glowstone_dust.png" };
    static {
        List<String> n = new ArrayList<>();
        for (C64Weapon w : C64Weapon.values()) { n.add(w.key + "_0"); n.add(w.key + "_1"); n.add(w.key + "_2"); }
        NAMES = n.toArray(new String[0]);
    }
}
